[package]
name = "tetrust"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[build-dependencies]
winres = "0.1"

[dependencies]
piston_window = "0.124.0"
rodio = "0.16.0"
rand = "0.8.5"
native-dialog = "0.6.3"